title: Josh Quiachon
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://dev.quiachonj.us/" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Josh Quiachon # add your name
author-img: head-shot-new.png # add your photo
author-about: Hello!, My name is
author-title: |
 I am a
 Software Engineer
 .NET Full-Stack Developer
 Azure Developer
 Solutions Architect
author-stack: | # add tech stack
 C#
 ASP.Net
 Azure
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: quiachonj # add your Github handle
social-linkedin: quiachonj # add your Linkedin handle
social-email: josh@quiachonj.us # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
