services:
  jekyll:
    container_name: quiachonj.github.io
    image: jekyll/jekyll:latest
    working_dir: /srv/jekyll
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --watch --force_polling --host 0.0.0.0
